name: Playwright Tests
on:
  push:
    branches: [ main, master,test/e2e ]
  pull_request:
    branches: [ main, master , test/e2e ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn

